In [12]:
import pandas as pd
import json
from pathlib import Path 
import os

In [13]:

def parse_wpl_json(file_path):
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    # Extract metadata from the 'info' section
    match_id = os.path.basename(file_path).split('.')[0]
    city = data['info'].get('city', 'Unknown')
    date = data['info']['dates'][0]
    
    ball_data = []
    
    for inning_num, inning in enumerate(data['innings']):
        team_batting = inning['team']
        # Find who the bowling team is
        teams = data['info']['teams']
        team_bowling = [t for t in teams if t != team_batting][0]
        
        for over_data in inning['overs']:
            over_num = over_data['over']
            
            for ball_num, delivery in enumerate(over_data['deliveries']):
                # Basic info
                record = {
                    'match_id': match_id,
                    'date': date,
                    'inning': inning_num + 1,
                    'batting_team': team_batting,
                    'bowling_team': team_bowling,
                    'over': over_num,
                    'ball': ball_num + 1,
                    'batter': delivery['batter'],
                    'bowler': delivery['bowler'],
                    'non_striker': delivery['non_striker'],
                    'runs_bat': delivery['runs']['batter'],
                    'runs_extras': delivery['runs']['extras'],
                    'runs_total': delivery['runs']['total']
                }
                
                # Check for Wides/No Balls (important for balls faced/bowled)
                if 'extras' in delivery:
                    record['is_wide'] = 1 if 'wides' in delivery['extras'] else 0
                    record['is_noball'] = 1 if 'noballs' in delivery['extras'] else 0
                else:
                    record['is_wide'] = 0
                    record['is_noball'] = 0
                
                # Check for Wickets
                if 'wickets' in delivery:
                    record['is_wicket'] = 1
                    record['player_out'] = delivery['wickets'][0]['player_out']
                    record['wicket_kind'] = delivery['wickets'][0]['kind']
                else:
                    record['is_wicket'] = 0
                    record['player_out'] = None
                    record['wicket_kind'] = None
                
                ball_data.append(record)
                
    return pd.DataFrame(ball_data)

In [ ]:
script_dir = Path(__file__).resolve().parent if "__file__" in locals() else Path.cwd()
data_folder = script_dir.parent / 'data' / '01_raw_data' / 'wpl_json'

dfs_list = []

if data_folder.exists() and data_folder.is_dir():
    json_files = list(data_folder.glob('*.json'))
    print(f"Found {len(json_files)} files in: {data_folder}")

    for file_path in json_files:
        try:
            df = parse_wpl_json(file_path)
            
            # Ensure we aren't adding empty DFs that might mess up types
            if not df.empty:
                dfs_list.append(df)
                
        except Exception as e:
            # specifically catching json.JSONDecodeError is often helpful here
            print(f"Error parsing {file_path.name}: {e}")

    # 4. Final Aggregation
    if dfs_list:
        # ignore_index=True is perfect here to create a fresh 0..N index
        all_content = pd.concat(dfs_list, ignore_index=True)
        print(f"Success: Combined {len(dfs_list)} files into {all_content.shape[0]} rows.")
    else:
        print("No valid data was parsed.")
        all_content = pd.DataFrame()
else:
    print(f"Directory not found: {data_folder}")

all_content.head()

Found 22 files in: /home/mohan/Projects/wpl-2026-analysis/data/01_raw_data/wpl_json
✅ Success: Combined 22 files into 5250 rows.

,match_id,date,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,runs_bat,runs_extras,runs_total,is_wide,is_noball,is_wicket,player_out,wicket_kind
0,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,1,HK Matthews,LK Bell,S Sajana,4,0,4,0,0,0,None,None
1,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,2,HK Matthews,LK Bell,S Sajana,0,0,0,0,0,0,None,None
2,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,3,HK Matthews,LK Bell,S Sajana,0,1,1,1,0,0,None,None
3,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,4,HK Matthews,LK Bell,S Sajana,0,0,0,0,0,0,None,None
4,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,5,HK Matthews,LK Bell,S Sajana,1,0,1,0,0,0,None,None

In [15]:
all_content

,match_id,date,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,runs_bat,runs_extras,runs_total,is_wide,is_noball,is_wicket,player_out,wicket_kind
0,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,1,HK Matthews,LK Bell,S Sajana,4,0,4,0,0,0,None,None
1,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,2,HK Matthews,LK Bell,S Sajana,0,0,0,0,0,0,None,None
2,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,3,HK Matthews,LK Bell,S Sajana,0,1,1,1,0,0,None,None
3,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,4,HK Matthews,LK Bell,S Sajana,0,0,0,0,0,0,None,None
4,1513697,2026-01-26,1,Mumbai Indians,Royal Challengers Bengaluru,0,5,HK Matthews,LK Bell,S Sajana,1,0,1,0,0,0,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,1513699,2026-01-29,2,Royal Challengers Bengaluru,UP Warriorz,12,3,S Mandhana,S Asha,G Voll,0,0,0,0,0,0,None,None
5246,1513699,2026-01-29,2,Royal Challengers Bengaluru,UP Warriorz,12,4,S Mandhana,S Asha,G Voll,0,0,0,0,0,0,None,None
5247,1513699,2026-01-29,2,Royal Challengers Bengaluru,UP Warriorz,12,5,S Mandhana,S Asha,G Voll,1,0,1,0,0,0,None,None
5248,1513699,2026-01-29,2,Royal Challengers Bengaluru,UP Warriorz,12,6,G Voll,S Asha,S Mandhana,0,0,0,0,0,1,G Voll,caught
5249,1513699,2026-01-29,2,Royal Challengers Bengaluru,UP Warriorz,13,1,S Mandhana,DB Sharma,RM Ghosh,4,0,4,0,0,0,None,None

In [16]:
all_content[
    (all_content['is_wicket'] != 0) & (all_content['bowler'] == 'NSS Sharma')
]

,match_id,date,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,runs_bat,runs_extras,runs_total,is_wide,is_noball,is_wicket,player_out,wicket_kind
792,1513688,2026-01-14,1,UP Warriorz,Delhi Capitals,15,4,MM Lanning,NSS Sharma,H Deol,0,0,0,0,0,1,MM Lanning,caught
1505,1513685,2026-01-11,1,Gujarat Giants,Delhi Capitals,10,5,SFM Devine,NSS Sharma,A Gardner,0,0,0,0,0,1,SFM Devine,caught
1558,1513685,2026-01-11,1,Gujarat Giants,Delhi Capitals,19,2,KS Gautam,NSS Sharma,KS Ahuja,0,0,0,0,0,1,KS Gautam,caught
1560,1513685,2026-01-11,1,Gujarat Giants,Delhi Capitals,19,4,KS Ahuja,NSS Sharma,TP Kanwar,0,0,0,0,0,1,KS Ahuja,stumped
1561,1513685,2026-01-11,1,Gujarat Giants,Delhi Capitals,19,5,RS Gayakwad,NSS Sharma,TP Kanwar,0,0,0,0,0,1,RS Gayakwad,bowled
1562,1513685,2026-01-11,1,Gujarat Giants,Delhi Capitals,19,6,Renuka Singh,NSS Sharma,TP Kanwar,0,0,0,0,0,1,Renuka Singh,bowled
1787,1513698,2026-01-27,1,Gujarat Giants,Delhi Capitals,16,3,BL Mooney,NSS Sharma,KS Ahuja,0,0,0,0,0,1,BL Mooney,caught
2223,1513684,2026-01-10,1,Mumbai Indians,Delhi Capitals,6,3,G Kamalini,NSS Sharma,NR Sciver-Brunt,0,0,0,0,0,1,G Kamalini,caught
2297,1513684,2026-01-10,1,Mumbai Indians,Delhi Capitals,18,3,NJ Carey,NSS Sharma,H Kaur,0,0,0,0,0,1,NJ Carey,bowled
2533,1513696,2026-01-24,1,Royal Challengers Bengaluru,Delhi Capitals,17,3,A Reddy,NSS Sharma,N de Klerk,0,0,0,0,0,1,A Reddy,lbw
2546,1513696,2026-01-24,1,Royal Challengers Bengaluru,Delhi Capitals,19,4,SR Patil,NSS Sharma,SG Satghare,0,0,0,0,0,1,SR Patil,caught
2548,1513696,2026-01-24,1,Royal Challengers Bengaluru,Delhi Capitals,19,6,SG Satghare,NSS Sharma,LK Bell,0,0,0,0,0,1,SG Satghare,bowled
2668,1513694,2026-01-20,1,Mumbai Indians,Delhi Capitals,3,5,S Sajana,NSS Sharma,HK Matthews,0,0,0,0,0,1,S Sajana,bowled
3600,1513703,2026-02-05,2,Royal Challengers Bengaluru,Delhi Capitals,17,4,RM Ghosh,NSS Sharma,S Mandhana,0,0,0,0,0,1,RM Ghosh,caught
3884,1513702,2026-02-03,1,Gujarat Giants,Delhi Capitals,5,1,AB Sharma,NSS Sharma,BL Mooney,0,0,0,0,0,1,AB Sharma,caught
3885,1513702,2026-02-03,1,Gujarat Giants,Delhi Capitals,5,2,A Gardner,NSS Sharma,BL Mooney,0,0,0,0,0,1,A Gardner,caught
3978,1513702,2026-02-03,1,Gujarat Giants,Delhi Capitals,19,6,BL Mooney,NSS Sharma,KS Gautam,1,0,1,0,0,1,KS Gautam,run out
4551,1513692,2026-01-17,2,Royal Challengers Bengaluru,Delhi Capitals,17,2,S Mandhana,NSS Sharma,G Voll,0,0,0,0,0,1,S Mandhana,caught

In [ ]:
all_content.to_csv(r'D:\Projects\wpl_analysis\data\02_cleaned_da\cleaned_data',index=False)